### PR TITLE
Fix the code which determines whether or not a value is a weak ref.

### PR DESCRIPTION
**Pull request by danfuzz**
This fixes issue #83.

### CODE REVIEW

**Comment by danfuzz** [comment]
Likewise, the Appveyor build failed only on v3.

**Comment by danfuzz** [comment]
Per this comment I ran across in `nan` <https://github.com/nodejs/nan/issues/676#issuecomment-307793125> and this corroborating commit in `node-gyp` <https://github.com/nodejs/node-gyp/commit/75cfae290fee1791a23fa68820ae5dd841e93e14>, `node-gyp` no longer supports versions of Node older than v4. So, it is unsurprising to see the sort of failure I report above. 

Perhaps it is time to revise the Travis and Appveyor configurations?

**Comment by danfuzz** [comment]
Ping?

**Comment by TooTallNate** [comment]
Very nice!

**Pull request merged**
